/**
 * What the degree catalogue is missing, country by country and school by
 * school: which institutions have no record yet, which listed schools have
 * degrees without the Danish-standard detail, and which have no photograph.
 *
 *   node scripts/coverage-report.mjs            # writes docs/research/schools/COVERAGE.md
 *   node scripts/coverage-report.mjs --stdout   # prints it instead
 *
 * It reads only files in the repository, so it runs anywhere, and it is a
 * report, not a guard: it never fails.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const read = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));

const manifest = read('docs/research/schools/manifest.json');
const images = read('data/images.json');
const programmeImages = read('data/programme-images.json');
const leadsDir = path.join(ROOT, 'docs/research/schools/leads');
const hasLeads = (cc) => fs.existsSync(path.join(leadsDir, `${cc}.md`));

const record = (key) => {
  const p = path.join(ROOT, 'data/schools', `${key}.json`);
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : null;
};

// A degree meets the Danish standard when it says what it is and how places
// are decided. `needs` is left out: a degree with no subject requirement
// rightly has none.
const DETAIL = ['about', 'selection'];
const detailed = (p) => DETAIL.every((f) => p[f] != null && (!Array.isArray(p[f]) || p[f].length));
const ownPhoto = (key, p) => {
  const slug = (p.slug || p.name || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return Boolean(programmeImages[`programme-${key}-${slug}`]);
};

const countries = [];
const totals = { institutions: 0, records: 0, listed: 0, catalogue: 0, none: 0, degrees: 0, detailed: 0, ownPhoto: 0, schoolPhoto: 0, flagshipsDone: 0 };

for (const [cc, entry] of Object.entries(manifest).sort()) {
  const rows = [];
  const c = { cc, name: entry.country, institutions: entry.institutions.length, records: 0, degrees: 0, detailed: 0, ownPhoto: 0, schoolPhoto: 0, scopes: { listed: 0, catalogue: 0, none: 0 }, leads: hasLeads(cc) };
  for (const inst of entry.institutions) {
    const r = record(inst.key);
    const photo = Boolean(images[inst.key]);
    if (photo) c.schoolPhoto++;
    if (!r) { rows.push({ key: inst.key, name: inst.name, state: 'no record', photo }); continue; }
    c.records++;
    c.scopes[r.scope] = (c.scopes[r.scope] || 0) + 1;
    const ps = r.programmes || [];
    const d = ps.filter(detailed).length;
    const o = ps.filter((p) => ownPhoto(inst.key, p)).length;
    c.degrees += ps.length; c.detailed += d; c.ownPhoto += o;
    const gaps = [];
    if (r.scope === 'listed' && !ps.length) gaps.push('listed but no degrees');
    if (ps.length && d < ps.length) gaps.push(`${ps.length - d} of ${ps.length} degrees lack about/selection`);
    if (ps.length && o < ps.length) gaps.push(`${ps.length - o} of ${ps.length} degrees have no photo of their own`);
    if (r.scope === 'catalogue' && !(r.flagships || []).length) gaps.push('no flagships or faculties yet');
    if (!photo) gaps.push('no school photo');
    rows.push({ key: inst.key, name: inst.name, state: r.scope, degrees: ps.length, gaps, photo });
  }
  totals.institutions += c.institutions; totals.records += c.records;
  for (const s of ['listed', 'catalogue', 'none']) totals[s] += c.scopes[s] || 0;
  totals.degrees += c.degrees; totals.detailed += c.detailed; totals.ownPhoto += c.ownPhoto; totals.schoolPhoto += c.schoolPhoto;
  countries.push({ ...c, rows });
}

const pct = (a, b) => (b ? `${Math.round((100 * a) / b)}%` : '–');
const out = [];
out.push('# Degree catalogue coverage');
out.push('');
out.push(`Generated by \`node scripts/coverage-report.mjs\` from the repository on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand; re-run it after a research batch.`);
out.push('');
out.push('Denmark and the Netherlands\' first five institutions are built from the canonical records (`data/institutions`, `data/programmes`) and are not counted here; this covers the ~450 institutions in `docs/research/schools/manifest.json`.');
out.push('');
out.push('## Totals');
out.push('');
out.push(`- Institutions with a record: **${totals.records} of ${totals.institutions}** (${pct(totals.records, totals.institutions)}); ${totals.listed} listed, ${totals.catalogue} catalogue, ${totals.none} none.`);
out.push(`- Degrees listed: **${totals.degrees}**; with about and selection (the Danish standard): **${totals.detailed}** (${pct(totals.detailed, totals.degrees)}).`);
out.push(`- Degrees with a photograph of their own (#54): **${totals.ownPhoto}** (${pct(totals.ownPhoto, totals.degrees)}). The rest show their school's photo.`);
out.push(`- Institutions with a school photo: **${totals.schoolPhoto} of ${totals.institutions}**.`);
out.push('');
out.push('## By country');
out.push('');
out.push('| Country | Records | Listed / catalogue / none | Degrees | Danish standard | Own photo | School photo | Leads |');
out.push('|---|---|---|---|---|---|---|---|');
for (const c of countries) {
  out.push(`| ${c.name} (${c.cc}) | ${c.records}/${c.institutions} | ${c.scopes.listed || 0} / ${c.scopes.catalogue || 0} / ${c.scopes.none || 0} | ${c.degrees} | ${c.degrees ? `${c.detailed} (${pct(c.detailed, c.degrees)})` : '–'} | ${c.degrees ? c.ownPhoto : '–'} | ${c.schoolPhoto}/${c.institutions} | ${c.leads ? `[yes](leads/${c.cc}.md)` : 'no'} |`);
}
out.push('');
out.push('## By institution');
out.push('');
out.push('Only institutions with something missing are listed.');
for (const c of countries) {
  const missing = c.rows.filter((r) => r.state === 'no record' || r.gaps?.length);
  if (!missing.length) continue;
  out.push('');
  out.push(`### ${c.name}`);
  out.push('');
  const none = missing.filter((r) => r.state === 'no record');
  if (none.length) out.push(`- **No record (${none.length}):** ${none.map((r) => `\`${r.key}\`${r.photo ? '' : ' (no photo)'}`).join(', ')}`);
  for (const r of missing.filter((x) => x.state !== 'no record')) out.push(`- \`${r.key}\` (${r.state}, ${r.degrees} degrees): ${r.gaps.join('; ')}`);
}
out.push('');

const text = out.join('\n');
if (process.argv.includes('--stdout')) process.stdout.write(text);
else {
  fs.writeFileSync(path.join(ROOT, 'docs/research/schools/COVERAGE.md'), text);
  console.log(`Wrote docs/research/schools/COVERAGE.md: ${totals.records}/${totals.institutions} records, ${totals.degrees} degrees, ${totals.detailed} to the Danish standard, ${totals.ownPhoto} with their own photo.`);
}
